/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poopr;

import javax.swing.JOptionPane;
import java.sql.*;
import pr.QUIZZPOO;

/**
 *
 * @author Malek
 */
public class jav extends javax.swing.JFrame {

    /**
     * Creates new form jav
     */
    public int choix=0;
    String No;
    int mark=0,correct=0;
    public jav() 
    {
           initComponents();

    }
      public void Submit(){
      String No=jTextField1.getText();
             if( !A1_Q1.isSelected() && !A2_Q1.isSelected() && !A3_Q1.isSelected() && !A1_Q2.isSelected() && !A2_Q2.isSelected() && !A3_Q2.isSelected() )
        {
            JOptionPane.showMessageDialog(null, "please select and answer");
        } else {

            if(A3_Q1.isSelected())
            {
                mark=mark+5;
                correct=correct+1;
            }
            if( A1_Q2.isSelected())
            {
                mark=mark+5;
             correct=correct+1;

            }
            if( A1_Q3.isSelected())
            {
                mark=mark+5;
                correct=correct+1;

            }
            
       try {
           
       Connection con=QUIZZPOO.getcon();
       Statement st=con.createStatement();
       st.executeUpdate("update etud set notejav='"+mark+"'where No='"+No+"'");
      
       
       }
       catch(Exception e )
       {}
    }
  }
    
    
    
         public jav(String No) {
        initComponents();
        jTextField1.setText(No);
        
        try 
        {
            
         Connection con=QUIZZPOO.getcon();
         Statement st=con.createStatement();
         ResultSet rs=st.executeQuery("select *from etud where No='"+No+"'");
          jTextField1.setEditable(false);

        }
        catch (Exception e )
        {}
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Q1bg = new javax.swing.ButtonGroup();
        Q2bg = new javax.swing.ButtonGroup();
        Q3bg = new javax.swing.ButtonGroup();
        Q4bg = new javax.swing.ButtonGroup();
        Q5bg = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        A1_Q1 = new javax.swing.JRadioButton();
        A2_Q1 = new javax.swing.JRadioButton();
        A3_Q1 = new javax.swing.JRadioButton();
        A1_Q2 = new javax.swing.JRadioButton();
        A2_Q2 = new javax.swing.JRadioButton();
        A3_Q2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        A1_Q3 = new javax.swing.JRadioButton();
        A2_Q3 = new javax.swing.JRadioButton();
        A3_Q3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("professeur:Dina ABDELI ");

        jLabel6.setText("QUESTION 2");

        jLabel7.setText("Which Map class should be most popular in a multi-threading environment, considering performance constraint?");

        Q1bg.add(A1_Q1);
        A1_Q1.setText(" HashSet ");
        A1_Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_Q1ActionPerformed(evt);
            }
        });

        Q1bg.add(A2_Q1);
        A2_Q1.setText(" ConcurrentSkipListSet ");
        A2_Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_Q1ActionPerformed(evt);
            }
        });

        Q1bg.add(A3_Q1);
        A3_Q1.setText("LinkedHashSet");

        Q2bg.add(A1_Q2);
        A1_Q2.setText("Hashtable");
        A1_Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1_Q2ActionPerformed(evt);
            }
        });

        Q2bg.add(A2_Q2);
        A2_Q2.setText("CopyOnWriteMap");
        A2_Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_Q2ActionPerformed(evt);
            }
        });

        Q2bg.add(A3_Q2);
        A3_Q2.setText("ConcurrentHashMap");
        A3_Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3_Q2ActionPerformed(evt);
            }
        });

        jLabel8.setText("QUESTION 3 ");

        jLabel9.setText("Which allows the removal of elements from a collection?");

        Q3bg.add(A1_Q3);
        A1_Q3.setText("Enumeration");

        Q3bg.add(A2_Q3);
        A2_Q3.setText("Iterator");
        A2_Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2_Q3ActionPerformed(evt);
            }
        });

        Q3bg.add(A3_Q3);
        A3_Q3.setText("None of the above");
        A3_Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3_Q3ActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Which Set class should be most popular in a multi-threading environment, considering performance constraint ?  ");

        jLabel4.setText("QUESTION 1 ");

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("-QUIZZ POO-");

        jLabel2.setText("Votre ID Etud ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButton1)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addGap(91, 91, 91))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A2_Q1)
                                    .addComponent(A3_Q1)
                                    .addComponent(A1_Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(A1_Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9))
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(A1_Q3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(A2_Q3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(A3_Q3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A3_Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A2_Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A1_Q1)
                .addGap(7, 7, 7)
                .addComponent(A2_Q1)
                .addGap(7, 7, 7)
                .addComponent(A3_Q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A1_Q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A2_Q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A3_Q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(A1_Q3)
                .addGap(7, 7, 7)
                .addComponent(A2_Q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A3_Q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1_Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_Q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1_Q1ActionPerformed

    private void A2_Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_Q1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2_Q1ActionPerformed

    private void A1_Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1_Q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1_Q2ActionPerformed

    private void A2_Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_Q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2_Q2ActionPerformed

    private void A3_Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3_Q2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3_Q2ActionPerformed

    private void A2_Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2_Q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2_Q3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Submit();
            choix=2;
           
                    setVisible(false);
               new Resultat(mark,correct,choix).setVisible(true);

        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void A3_Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3_Q3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3_Q3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jav.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jav("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A1_Q1;
    private javax.swing.JRadioButton A1_Q2;
    private javax.swing.JRadioButton A1_Q3;
    private javax.swing.JRadioButton A2_Q1;
    private javax.swing.JRadioButton A2_Q2;
    private javax.swing.JRadioButton A2_Q3;
    private javax.swing.JRadioButton A3_Q1;
    private javax.swing.JRadioButton A3_Q2;
    private javax.swing.JRadioButton A3_Q3;
    private javax.swing.ButtonGroup Q1bg;
    private javax.swing.ButtonGroup Q2bg;
    private javax.swing.ButtonGroup Q3bg;
    private javax.swing.ButtonGroup Q4bg;
    private javax.swing.ButtonGroup Q5bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
